version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: minglin-postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # PostGIS provides spatial extensions for geospatial queries

  web:
    build: .
    container_name: minglin-backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
    # Exposes Django app on port 8000

volumes:
  postgres_data:

# See README.md and inline comments for documentation. 