env_vars = {
    'DEBUG': False,
    'SECRET_KEY': 'b_5@#*s(#e)v1#6k!^@c32vm%iy(c&2-0@rfva%%v6z6hu^ky&',
    'JWT_SECRET_KEY': 'v1#6k!^@c32vm%iy(c&2-0@rfva%%v6z6hu^ky&',
    'KAZANG_BASE_URL': 'https://api.kazang.net/apimanager/api_rest/v1',
    'PROD_USERNAME': '8011819587',
    'PROD_PASSWORD': '$Zx&#CP!',
    'CHANNEL': 'PridePayments',
    'SERIAL_NUMBER': '162.0.234.213',
    'PROBASE_URL': 'https://probasesms.com/api/json/multi/res/bulk/sms',
    'PROBASE_USERNAME': 'All1Zed@12$$',
    'PROBASE_PASSWORD': 'All1Zed@sms12$$',
    'PROBASE_SENDER_ID': 'Tumingle',
    'PROBASE_SOURCE': 'Tumingle',
    'DB_ENGINE': 'django.db.backends.postgresql',
    'DB_DATABASE':'card_pay_db',
    'DB_USER': 'card_pay',
    'DB_PASSWORD': 'root2023!',
    'DB_HOST': 'db',
    'DB_HOST': '102.146.165.40',
    'DB_PORT': '5433',
    'DATABASE': 'postgres',
}
